spring:
  profiles:
    active: local
  application:
    name: AxolotlikCosmoCats

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /api-specs/market-api-spec.yml
    disable-swagger-default-url: true
  api-docs:
    enabled: true

application:
  feature:
    cosmo-cats: true
    kitty-products: false

---
spring:
  config:
    activate:
      on-profile: dev
application:
  feature:
    cosmo-cats: false
